version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: spring-mysql
    ports:
      - "3326:3306" # HOST:CONTAINER
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
